services:
  garage-simulator:
    image: cfontes0estapar/garage-sim:1.0.0
    container_name: garage-simulator
    ports:
      - "3004:3000"
    networks:
      - parking-net

  parking-manager:
    build: .
    container_name: parking-manager
    ports:
      - "3003:3003"
    environment:
      SERVER_PORT: 3003
      SPRING_DATASOURCE_URL: jdbc:mysql://parking-mysql:3306/parkingdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin123
      SIMULATOR_BASE_URL: http://garage-simulator:3000
    depends_on:
      - parking-mysql
      - garage-simulator
    networks:
      - parking-net

  parking-mysql:
    image: mysql:8.0
    container_name: parking-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: parkingdb
    ports:
      - "3307:3306"
    networks:
      - parking-net

networks:
  parking-net:
