version: "3.9"

services:

  parking-mysql:
    image: mysql:8.0
    container_name: parking-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: parkingdb
    ports:
      - "3307:3306"
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      retries: 10

  parking-manager:
    build: .
    container_name: parking-manager
    restart: always
    depends_on:
      parking-mysql:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "3003:3003"
    # app conversa com MySQL e simulador dentro da rede
    networks:
      - parking-net

  garage-simulator:
    container_name: garage-simulator
    image: cfontes0estapar/garage-sim:1.0.0
    restart: always
    depends_on:
      - parking-manager
    environment:
      WEBHOOK_URL: http://parking-manager:3003/webhook
      EXTERNAL_API_URL: http://parking-manager:3003/webhook
    networks:
      - parking-net

networks:
  parking-net:
    driver: bridge
